"use client";

import { useState } from "react";
import Link from "next/link";
import clsx from "clsx";
import { Button, Card } from "@/components/ui";
import { useToast } from "@/components/Toast";
import { formatCurrency } from "@/lib/demo";

const METHODS = [
  { key: "upi", label: "UPI" },
  { key: "card", label: "Card" },
  { key: "netbanking", label: "Net Banking" },
];
const BANKS = ["State Bank of India", "HDFC Bank", "ICICI Bank", "Axis Bank", "Kotak Mahindra Bank"];

function fmtDate(v) {
  return new Date(v).toLocaleString("en-IN", { day: "2-digit", month: "long", year: "numeric", hour: "2-digit", minute: "2-digit" });
}

function SuccessView({ payment, project }) {
  return (
    <div className="max-w-xl mx-auto text-center pt-4">
      <div className="pop-in mx-auto mb-6 h-20 w-20 rounded-full bg-emerald-400/10 border border-emerald-400/30 flex items-center justify-center">
        <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#6ee7b7" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
          <path className="check-path" d="M5 12.5l4.5 4.5L19 7.5" />
        </svg>
      </div>
      <h1 className="text-3xl font-semibold tracking-tight mb-2">Payment Successful</h1>
      <p className="text-muted mb-6">Your project has been submitted for processing.</p>
      <div className="flex justify-center gap-2 mb-6 text-xs font-mono-ladion">
        <span className="badge border-emerald-400/30 text-emerald-300 bg-emerald-400/10">Email Sent {"\u2713"}</span>
        <span className="badge border-emerald-400/30 text-emerald-300 bg-emerald-400/10">WhatsApp Sent {"\u2713"}</span>
      </div>
      <Card className="text-left p-6 space-y-3 mb-6">
        {[
          ["Project", project.name],
          ["Amount", formatCurrency(payment.amount, payment.currency)],
          ["Order ID", payment.order_id],
          ["Payment ID", payment.payment_ref],
          ["Transaction", payment.transaction_id],
          ["Date", payment.paid_at ? fmtDate(payment.paid_at) : "\u2014"],
        ].map(([k, v]) => (
          <div key={k} className="flex justify-between gap-4 text-sm">
            <span className="text-muted">{k}</span>
            <span className="font-medium font-mono-ladion text-right break-all">{v}</span>
          </div>
        ))}
        <p className="text-[11px] text-amber-200/80 font-mono-ladion pt-2 border-t border-white/10">
          SIMULATED &mdash; these references were generated by the demo payment provider. No money was charged.
        </p>
      </Card>
      <div className="flex justify-center gap-3 flex-wrap">
        <Button as={Link} href={`/client/projects/${project.id}`} variant="solid">View project</Button>
        <Button as={Link} href="/client/dashboard">Go to dashboard</Button>
        <Button as={Link} href="/client/notifications" variant="ghost">View notifications</Button>
      </div>
    </div>
  );
}

export function PaymentGateway({ payment: initial, demoMode }) {
  const { toast } = useToast();
  const [payment, setPayment] = useState(initial);
  const [method, setMethod] = useState("upi");
  const [phase, setPhase] = useState(initial.status === "paid" ? "success" : "idle"); // idle | processing | success | failed
  const [failReason, setFailReason] = useState("");
  const [simulateFailure, setSimulateFailure] = useState(false);
  const project = initial.projects;
  const amountText = formatCurrency(payment.amount, payment.currency);

  async function pay() {
    setPhase("processing");
    try {
      const res = await fetch(`/api/payments/${payment.id}/pay`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ method, simulateFailure }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || "Payment could not be processed.");
      setPayment(json.payment);
      if (json.payment.status === "paid") {
        setPhase("success");
        toast("Payment received. Confirmation sent by email and WhatsApp.", "success");
      } else {
        setFailReason("The payment was declined by the payment provider.");
        setPhase("failed");
      }
    } catch (err) {
      setFailReason(err.message);
      setPhase("failed");
    }
  }

  if (phase === "success") return <SuccessView payment={payment} project={project} />;

  if (payment.status === "cancelled") {
    return (
      <div className="max-w-md mx-auto text-center pt-10">
        <h1 className="text-2xl font-semibold mb-2">Payment request cancelled</h1>
        <p className="text-muted mb-6">This payment request is no longer active.</p>
        <Button as={Link} href="/client/dashboard">Back to dashboard</Button>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto fade-up">
      <div className="mb-6 rounded-lg border border-amber-400/25 bg-amber-400/[0.06] px-4 py-2.5 text-xs font-mono-ladion text-amber-200">
        SIMULATION / DEMO PAYMENT &mdash; no real money is charged and no real bank details are needed.
      </div>

      <div className="grid md:grid-cols-5 gap-6">
        {/* order summary */}
        <Card className="md:col-span-2 p-6 h-fit">
          <div className="flex items-baseline gap-2 mb-6">
            <span className="font-bold tracking-wide">LADION</span>
            <span className="font-mono-ladion text-[10px] tracking-widest text-muted">TECHNOLOGIES</span>
          </div>
          <div className="text-xs font-mono-ladion text-muted mb-1">PAYMENT FOR</div>
          <div className="font-medium mb-1">{project.name}</div>
          <div className="text-sm text-muted mb-5">{payment.description}</div>
          <div className="space-y-2 text-sm border-t border-white/10 pt-4">
            <div className="flex justify-between"><span className="text-muted">Reference</span><span className="font-mono-ladion">{payment.payment_code}</span></div>
            <div className="flex justify-between"><span className="text-muted">Subtotal</span><span>{amountText}</span></div>
            <div className="flex justify-between"><span className="text-muted">Taxes</span><span>{"\u2014"}</span></div>
            <div className="flex justify-between text-lg font-semibold pt-2 border-t border-white/10"><span>Total</span><span>{amountText}</span></div>
          </div>
        </Card>

        {/* method + pay */}
        <Card className="md:col-span-3 p-6">
          <h2 className="text-lg font-semibold mb-4">Choose a payment method</h2>
          <div className="grid grid-cols-3 gap-2 mb-6">
            {METHODS.map((m) => (
              <button
                key={m.key} type="button" onClick={() => setMethod(m.key)} disabled={phase === "processing"}
                className={clsx(
                  "rounded-lg border py-2.5 text-sm transition-all",
                  method === m.key ? "border-accent bg-accent/10 text-fg" : "border-white/10 text-muted hover:border-white/25"
                )}
              >
                {m.label}
              </button>
            ))}
          </div>

          <div className="space-y-4 mb-6">
            {method === "upi" && (
              <div>
                <label className="field-label">UPI ID</label>
                <input className="field-input" placeholder="name@bank" autoComplete="off" />
              </div>
            )}
            {method === "card" && (
              <>
                <div>
                  <label className="field-label">Card number</label>
                  <input className="field-input" placeholder="4111 1111 1111 1111" autoComplete="off" />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div><label className="field-label">Expiry</label><input className="field-input" placeholder="MM / YY" autoComplete="off" /></div>
                  <div><label className="field-label">CVV</label><input className="field-input" placeholder="123" autoComplete="off" /></div>
                </div>
              </>
            )}
            {method === "netbanking" && (
              <div>
                <label className="field-label">Select your bank</label>
                <select className="field-input">{BANKS.map((b) => <option key={b}>{b}</option>)}</select>
              </div>
            )}
            <p className="text-xs text-muted">Demo only: any values are accepted, none are stored or sent anywhere.</p>
          </div>

          {demoMode && (
            <label className="flex items-center gap-2 text-xs text-muted mb-4 cursor-pointer">
              <input type="checkbox" checked={simulateFailure} onChange={(e) => setSimulateFailure(e.target.checked)} />
              Demo control: simulate a failed payment
            </label>
          )}

          {phase === "failed" && (
            <div className="mb-4 rounded-lg border border-rose-400/30 bg-rose-400/[0.07] px-4 py-3 text-sm text-rose-200">
              <div className="font-medium mb-0.5">Payment failed</div>
              {failReason} You have not been charged. Please try again.
            </div>
          )}

          <Button variant="solid" className="w-full py-3" onClick={pay} disabled={phase === "processing"}>
            {phase === "processing" ? (
              <span className="flex items-center gap-2">
                <span className="h-4 w-4 rounded-full border-2 border-[#08111a]/30 border-t-[#08111a] animate-spin" />
                Processing Payment{"\u2026"}
              </span>
            ) : phase === "failed" ? `Retry ${amountText}` : `Pay ${amountText}`}
          </Button>
        </Card>
      </div>
    </div>
  );
}
